#!/bin/bash
#
#  genstimulus-2
#
#  This shell script generates the stimuli for the experiment.
#
#  Copyright (C) 2006, 2017 Tak-Shing Chan
#

# Downloading esacfiles
mkdir -p esacfiles
cd esacfiles
curl http://www.esac-data.org/disks/disk3/kinder0.sm | tr -d '\r' | ../../utilities/shares.pl | sh
cd ..

# Importing esacfiles
mkdir -p notefiles/chan nbfiles/chan opmfiles/chan
for i in esacfiles/K*; do
    echo Importing $i...
    j=chan/`basename $i`
    ../utilities/esac -k C < $i > notefiles/$j.notes
    ../utilities/melisma2003/meter/meter notefiles/$j.notes > nbfiles/$j.nb
    ../utilities/nb2opm nbfiles/$j.nb > opmfiles/$j.opm
done

# Creating the listener file
echo Creating chan/listener.opm...
../utilities/opmcat opmfiles/chan/K1*.opm > opmfiles/chan/listener.opm

# Mutating opmfiles
for i in opmfiles/chan/K{2445,3027}.opm; do
    for ((j = 1; j <= 22; j++)); do
        echo Mutating $i \(iteration $j\)...
        mkdir -p opmfiles/chan/mutations/`basename $i .opm`/$j
        cd opmfiles/chan/mutations/`basename $i .opm`/$j
        ../../../../../../utilities/mutate ../../../../../$i | sh
        cd ../../../../..
    done
done

# Converting opmfiles to midifiles
mkdir -p midifiles
for i in opmfiles/chan/mutations/K{2445,3027}; do
    echo Converting $i and its mutations...
    j=`basename $i`
    ../utilities/opm2mid $i/1/0.opm midifiles/$j-1-0.mid
    for ((k = 1; k <= 22; k++)); do
        ../utilities/opm2mid $i/$k/5.opm midifiles/$j-$k-5.mid
        ../utilities/opm2mid $i/$k/10.opm midifiles/$j-$k-10.mid
        ../utilities/opm2mid $i/$k/15.opm midifiles/$j-$k-15.mid
        ../utilities/opm2mid $i/$k/20.opm midifiles/$j-$k-20.mid
    done
done
